---
title: "Untitled"
author: "Digitize"
date: "2/12/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#setwd(githubdir)
#setwd("running_analysis")

## Load the libraries
library("tidyverse")
library("lubridate")

## Load the data and preprocess it
## Variable names are all uppercase and include spaces, reduce data to only Running,
## and clean up the variables of interest + generate date variables for plot and regression
df_garmin <- read_csv("~/Dropbox/Research/Repos/running_analysis/data/garmin.csv") %>% 
  select_all(~gsub("\\s+|\\.", "_", .)) %>% 
  select_all(tolower) %>% 
  filter(activity_type == "Running") %>% 
  separate(date, into = c("date", "time"), sep = " ") %>% 
  mutate_all(str_replace_all, ",|:", ".") %>% 
  mutate(across(c(distance, avg_pace, avg_hr, elev_gain, calories), as.numeric),
         date = ymd(date), 
         year =  year(date),
         month = month(date),
         year_month =  ym(paste(year, month)),
         month_char = lubridate::month(as.numeric(month), label = TRUE)) %>% 
  filter(distance > 0.99)


## Load the library
library("tidyverse")
library("texreg")
library("corrplot")

## Reduce data frame to variables used in the analysis
df_analysis <-
  df_garmin %>% 
  dplyr::select(distance, year, avg_pace, avg_hr, elev_gain, calories) %>% 
  mutate(km10 = ifelse(distance > 10.5, TRUE, FALSE))


```

## R Markdown

```{r pressure, echo=FALSE, results='asis'}
# Model 1: Has the distance changed over time?
lm1 <- lm(distance ~ year, data = df_analysis)

# Model 2: What explains variation in my avg. heart rate? Bivariate model with pace
lm2 <- lm(avg_hr ~ avg_pace, data = df_analysis)

# Model 3: What explains variation in my avg. heart rate? Multivariate model with other covariates
# Unfortunately I don't have weather 
lm3 <- lm(avg_hr ~ distance + km10 + avg_pace + elev_gain + year, data = df_analysis)

# Model 4: What explains variation in my average pace?
lm4 <- lm(avg_pace ~ distance + km10 + elev_gain + year, data = df_analysis)

# Model 5: What explains variation in my estimated calories for the run
lm5 <- lm(calories ~ distance + km10 + avg_pace + elev_gain + year, data = df_analysis)


## Export table to Latex
texreg(list(lm1, lm2, lm3, lm4, lm5),
          custom.model.names = c("Distance", "Avg. HR", "Avg. HR", "Avg. Pace", "Calories"),
          custom.coef.names = c("Intercept", "Year", "Avg. Pace", "Distance", "more than 10k", "Elevation Gain"),
          omit.coef = "Intercept",
          caption="Regression models", 
          caption.above = TRUE,
          custom.note = "All models are ordinary least squares regressions.",
          include.rs=TRUE, 
          include.adjrs = FALSE,
          digits=2,
          stars=c(0.01, 0.05, 0.1))


```
